### ISSUE TITLE
app-sider什么时候会被隐藏？

### ISSUE THREAD

**Issue by hahahaha123567** [mingzuozhibi/mzzb-ui#1]
不太懂移动端的适配，app-sider.tsx中声明了函数setViewSider()和onCollapse，在app-header.tsx中单击按钮会被调用，但是找不到隐藏过程的实现和改变窗口大小的时候为什么会被调用

**Comment by hahahaha123567** [comment]
找到了引用的antd库，还是谢谢

**Comment by fuhaiwei** [comment]
本项目使用了redux来管理全局状态，其中侧边栏的隐藏是由store.app.viewSider这个变量所控制的，通过传入antd<Layout.Sider collapsed={!props.viewSider}>（src/App/app-sider/app-sider.tsx 72行）

这个变量的改变是通过src/App/reducer.tsx 42行控制的。其他地方只要 dispatch({type: 'setViewSider', viewSider: true})

至于改变窗口大小时自动显示隐藏是antd提供的回调函数，function onCollapse(hideSider: boolean, type: 'clickTrigger' | 'responsive')。

**Comment by fuhaiwei** [comment]
自动隐藏的宽度是通过 breakpoint="md" 参数控制的，我没记错的话应该是md=768px。

**Comment by fuhaiwei** [comment]
其实你自己想用react实现通过变量隐藏组件也很简单
如
```javascript
                {hasBasicRole && (
                  <Breadcrumb.Item>
                    <Link to={`/admin${match.url}`}>跳转到后台模式</Link>
                  </Breadcrumb.Item>
                )}
```
https://github.com/mingzuozhibi/mzzb-ui/blob/165c24ec07e55b18779da29e09b9ac432686c29b/src/components/sakura/sakura.tsx#L90

**Comment by hahahaha123567** [comment]
明白了，非常感谢
