### ISSUE TITLE
建議在列表中加入【原標題】欄目選項。

### ISSUE THREAD

**Issue by c933103** [mingzuozhibi/mzzb-ui#2]
以方便不認識中文的用戶使用…

**Comment by fuhaiwei** [comment]
原先日本运营的PT网站还在时，确实没有考虑到非中文用户的需求。
另外如果您有更多网站运营的想法可以来这个帖子留言。
https://tieba.baidu.com/p/5848378452
如果@fuhaiwei的话，我就能及时收到通知了。
